# Generated by Django 4.0.4 on 2022-05-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
