# Generated by Django 4.1 on 2022-08-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_color_size_product_status_variaants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variaants',
            name='color_variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
        migrations.AlterField(
            model_name='variaants',
            name='product_variants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='home.product'),
        ),
        migrations.AlterField(
            model_name='variaants',
            name='size_variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
    ]
